import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-700 px-2 py-3 flex gap-5">
        < Link href="/">Home</Link>
        <Link  href="/dashboard">Dashboard</Link >
        <Link href="/group">group</Link>
        <Link  href="/dashboard/analytics">analytics</Link >
        <Link  href="/dashboard/setting">setting</Link >
        <Link  href="/dashboard/setting/password">password</Link >
        <Link  href="/blog">blog </Link >
        <Link href="/contectus">contectus</Link>
        <Link href="/services">services</Link>
        <Link href="/aboutus">aboutus</Link>
       
        </header>
        {children}
        <footer className="bg-gray-500 flex justify-center py-3">
<p>&copy; 2023 - All rights reserved.</p>
</footer>
        </body> 
    </html>
  )
}

